#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlourideCare
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FluorideCareDB")]
	public partial class FluorideDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Antrian(tbl_Antrian instance);
    partial void Updatetbl_Antrian(tbl_Antrian instance);
    partial void Deletetbl_Antrian(tbl_Antrian instance);
    partial void Inserttbl_User(tbl_User instance);
    partial void Updatetbl_User(tbl_User instance);
    partial void Deletetbl_User(tbl_User instance);
    partial void Inserttbl_Diagnosa(tbl_Diagnosa instance);
    partial void Updatetbl_Diagnosa(tbl_Diagnosa instance);
    partial void Deletetbl_Diagnosa(tbl_Diagnosa instance);
    partial void Inserttbl_Dokter(tbl_Dokter instance);
    partial void Updatetbl_Dokter(tbl_Dokter instance);
    partial void Deletetbl_Dokter(tbl_Dokter instance);
    partial void Inserttbl_Jadwal(tbl_Jadwal instance);
    partial void Updatetbl_Jadwal(tbl_Jadwal instance);
    partial void Deletetbl_Jadwal(tbl_Jadwal instance);
    partial void Inserttbl_Obat(tbl_Obat instance);
    partial void Updatetbl_Obat(tbl_Obat instance);
    partial void Deletetbl_Obat(tbl_Obat instance);
    partial void Inserttbl_PembayaranDetail(tbl_PembayaranDetail instance);
    partial void Updatetbl_PembayaranDetail(tbl_PembayaranDetail instance);
    partial void Deletetbl_PembayaranDetail(tbl_PembayaranDetail instance);
    partial void Inserttbl_PembayaranMaster(tbl_PembayaranMaster instance);
    partial void Updatetbl_PembayaranMaster(tbl_PembayaranMaster instance);
    partial void Deletetbl_PembayaranMaster(tbl_PembayaranMaster instance);
    partial void Inserttbl_Ruangan(tbl_Ruangan instance);
    partial void Updatetbl_Ruangan(tbl_Ruangan instance);
    partial void Deletetbl_Ruangan(tbl_Ruangan instance);
    partial void Inserttbl_tipe(tbl_tipe instance);
    partial void Updatetbl_tipe(tbl_tipe instance);
    partial void Deletetbl_tipe(tbl_tipe instance);
    #endregion
		
		public FluorideDBDataContext() : 
				base(global::FlourideCare.Properties.Settings.Default.FluorideCareDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public FluorideDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FluorideDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FluorideDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FluorideDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Antrian> tbl_Antrians
		{
			get
			{
				return this.GetTable<tbl_Antrian>();
			}
		}
		
		public System.Data.Linq.Table<tbl_User> tbl_Users
		{
			get
			{
				return this.GetTable<tbl_User>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Diagnosa> tbl_Diagnosas
		{
			get
			{
				return this.GetTable<tbl_Diagnosa>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Dokter> tbl_Dokters
		{
			get
			{
				return this.GetTable<tbl_Dokter>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Jadwal> tbl_Jadwals
		{
			get
			{
				return this.GetTable<tbl_Jadwal>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Obat> tbl_Obats
		{
			get
			{
				return this.GetTable<tbl_Obat>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PembayaranDetail> tbl_PembayaranDetails
		{
			get
			{
				return this.GetTable<tbl_PembayaranDetail>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PembayaranMaster> tbl_PembayaranMasters
		{
			get
			{
				return this.GetTable<tbl_PembayaranMaster>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Ruangan> tbl_Ruangans
		{
			get
			{
				return this.GetTable<tbl_Ruangan>();
			}
		}
		
		public System.Data.Linq.Table<tbl_tipe> tbl_tipes
		{
			get
			{
				return this.GetTable<tbl_tipe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Antrian")]
	public partial class tbl_Antrian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _no_antrian;
		
		private string _id_ruangan;
		
		private int _id_user;
		
		private System.DateTime _tanggal;
		
		private EntitySet<tbl_Diagnosa> _tbl_Diagnosas;
		
		private EntityRef<tbl_User> _tbl_User;
		
		private EntityRef<tbl_Ruangan> _tbl_Ruangan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onno_antrianChanging(string value);
    partial void Onno_antrianChanged();
    partial void Onid_ruanganChanging(string value);
    partial void Onid_ruanganChanged();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void OntanggalChanging(System.DateTime value);
    partial void OntanggalChanged();
    #endregion
		
		public tbl_Antrian()
		{
			this._tbl_Diagnosas = new EntitySet<tbl_Diagnosa>(new Action<tbl_Diagnosa>(this.attach_tbl_Diagnosas), new Action<tbl_Diagnosa>(this.detach_tbl_Diagnosas));
			this._tbl_User = default(EntityRef<tbl_User>);
			this._tbl_Ruangan = default(EntityRef<tbl_Ruangan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_antrian", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string no_antrian
		{
			get
			{
				return this._no_antrian;
			}
			set
			{
				if ((this._no_antrian != value))
				{
					this.Onno_antrianChanging(value);
					this.SendPropertyChanging();
					this._no_antrian = value;
					this.SendPropertyChanged("no_antrian");
					this.Onno_antrianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ruangan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_ruangan
		{
			get
			{
				return this._id_ruangan;
			}
			set
			{
				if ((this._id_ruangan != value))
				{
					if (this._tbl_Ruangan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ruanganChanging(value);
					this.SendPropertyChanging();
					this._id_ruangan = value;
					this.SendPropertyChanged("id_ruangan");
					this.Onid_ruanganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int NOT NULL")]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					if (this._tbl_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="Date NOT NULL")]
		public System.DateTime tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Antrian_tbl_Diagnosa", Storage="_tbl_Diagnosas", ThisKey="id", OtherKey="id")]
		public EntitySet<tbl_Diagnosa> tbl_Diagnosas
		{
			get
			{
				return this._tbl_Diagnosas;
			}
			set
			{
				this._tbl_Diagnosas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_User_tbl_Antrian", Storage="_tbl_User", ThisKey="id_user", OtherKey="id_user", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_User tbl_User
		{
			get
			{
				return this._tbl_User.Entity;
			}
			set
			{
				tbl_User previousValue = this._tbl_User.Entity;
				if (((previousValue != value) 
							|| (this._tbl_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_User.Entity = null;
						previousValue.tbl_Antrians.Remove(this);
					}
					this._tbl_User.Entity = value;
					if ((value != null))
					{
						value.tbl_Antrians.Add(this);
						this._id_user = value.id_user;
					}
					else
					{
						this._id_user = default(int);
					}
					this.SendPropertyChanged("tbl_User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Ruangan_tbl_Antrian", Storage="_tbl_Ruangan", ThisKey="id_ruangan", OtherKey="id_ruangan", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Ruangan tbl_Ruangan
		{
			get
			{
				return this._tbl_Ruangan.Entity;
			}
			set
			{
				tbl_Ruangan previousValue = this._tbl_Ruangan.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Ruangan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Ruangan.Entity = null;
						previousValue.tbl_Antrians.Remove(this);
					}
					this._tbl_Ruangan.Entity = value;
					if ((value != null))
					{
						value.tbl_Antrians.Add(this);
						this._id_ruangan = value.id_ruangan;
					}
					else
					{
						this._id_ruangan = default(string);
					}
					this.SendPropertyChanged("tbl_Ruangan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Diagnosas(tbl_Diagnosa entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Antrian = this;
		}
		
		private void detach_tbl_Diagnosas(tbl_Diagnosa entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Antrian = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_User")]
	public partial class tbl_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_user;
		
		private string _nama;
		
		private string _jenis_kelamin;
		
		private System.DateTime _tanggal_lahir;
		
		private string _alamat;
		
		private string _kota;
		
		private int _kodepos;
		
		private string _telepon;
		
		private string _email;
		
		private EntitySet<tbl_Antrian> _tbl_Antrians;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void Onjenis_kelaminChanging(string value);
    partial void Onjenis_kelaminChanged();
    partial void Ontanggal_lahirChanging(System.DateTime value);
    partial void Ontanggal_lahirChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void OnkotaChanging(string value);
    partial void OnkotaChanged();
    partial void OnkodeposChanging(int value);
    partial void OnkodeposChanged();
    partial void OnteleponChanging(string value);
    partial void OnteleponChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public tbl_User()
		{
			this._tbl_Antrians = new EntitySet<tbl_Antrian>(new Action<tbl_Antrian>(this.attach_tbl_Antrians), new Action<tbl_Antrian>(this.detach_tbl_Antrians));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_kelamin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jenis_kelamin
		{
			get
			{
				return this._jenis_kelamin;
			}
			set
			{
				if ((this._jenis_kelamin != value))
				{
					this.Onjenis_kelaminChanging(value);
					this.SendPropertyChanging();
					this._jenis_kelamin = value;
					this.SendPropertyChanged("jenis_kelamin");
					this.Onjenis_kelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal_lahir", DbType="Date NOT NULL")]
		public System.DateTime tanggal_lahir
		{
			get
			{
				return this._tanggal_lahir;
			}
			set
			{
				if ((this._tanggal_lahir != value))
				{
					this.Ontanggal_lahirChanging(value);
					this.SendPropertyChanging();
					this._tanggal_lahir = value;
					this.SendPropertyChanged("tanggal_lahir");
					this.Ontanggal_lahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kota", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string kota
		{
			get
			{
				return this._kota;
			}
			set
			{
				if ((this._kota != value))
				{
					this.OnkotaChanging(value);
					this.SendPropertyChanging();
					this._kota = value;
					this.SendPropertyChanged("kota");
					this.OnkotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodepos", DbType="Int NOT NULL")]
		public int kodepos
		{
			get
			{
				return this._kodepos;
			}
			set
			{
				if ((this._kodepos != value))
				{
					this.OnkodeposChanging(value);
					this.SendPropertyChanging();
					this._kodepos = value;
					this.SendPropertyChanged("kodepos");
					this.OnkodeposChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telepon", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telepon
		{
			get
			{
				return this._telepon;
			}
			set
			{
				if ((this._telepon != value))
				{
					this.OnteleponChanging(value);
					this.SendPropertyChanging();
					this._telepon = value;
					this.SendPropertyChanged("telepon");
					this.OnteleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_User_tbl_Antrian", Storage="_tbl_Antrians", ThisKey="id_user", OtherKey="id_user")]
		public EntitySet<tbl_Antrian> tbl_Antrians
		{
			get
			{
				return this._tbl_Antrians;
			}
			set
			{
				this._tbl_Antrians.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Antrians(tbl_Antrian entity)
		{
			this.SendPropertyChanging();
			entity.tbl_User = this;
		}
		
		private void detach_tbl_Antrians(tbl_Antrian entity)
		{
			this.SendPropertyChanging();
			entity.tbl_User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Diagnosa")]
	public partial class tbl_Diagnosa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_diagnosa;
		
		private int _id;
		
		private string _hasil_diagnosa;
		
		private string _resep;
		
		private string _status;
		
		private EntitySet<tbl_PembayaranMaster> _tbl_PembayaranMasters;
		
		private EntityRef<tbl_Antrian> _tbl_Antrian;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_diagnosaChanging(string value);
    partial void Onid_diagnosaChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onhasil_diagnosaChanging(string value);
    partial void Onhasil_diagnosaChanged();
    partial void OnresepChanging(string value);
    partial void OnresepChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public tbl_Diagnosa()
		{
			this._tbl_PembayaranMasters = new EntitySet<tbl_PembayaranMaster>(new Action<tbl_PembayaranMaster>(this.attach_tbl_PembayaranMasters), new Action<tbl_PembayaranMaster>(this.detach_tbl_PembayaranMasters));
			this._tbl_Antrian = default(EntityRef<tbl_Antrian>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_diagnosa", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_diagnosa
		{
			get
			{
				return this._id_diagnosa;
			}
			set
			{
				if ((this._id_diagnosa != value))
				{
					this.Onid_diagnosaChanging(value);
					this.SendPropertyChanging();
					this._id_diagnosa = value;
					this.SendPropertyChanged("id_diagnosa");
					this.Onid_diagnosaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					if (this._tbl_Antrian.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasil_diagnosa", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string hasil_diagnosa
		{
			get
			{
				return this._hasil_diagnosa;
			}
			set
			{
				if ((this._hasil_diagnosa != value))
				{
					this.Onhasil_diagnosaChanging(value);
					this.SendPropertyChanging();
					this._hasil_diagnosa = value;
					this.SendPropertyChanged("hasil_diagnosa");
					this.Onhasil_diagnosaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resep", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string resep
		{
			get
			{
				return this._resep;
			}
			set
			{
				if ((this._resep != value))
				{
					this.OnresepChanging(value);
					this.SendPropertyChanging();
					this._resep = value;
					this.SendPropertyChanged("resep");
					this.OnresepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Diagnosa_tbl_PembayaranMaster", Storage="_tbl_PembayaranMasters", ThisKey="id_diagnosa", OtherKey="id_diagnosa")]
		public EntitySet<tbl_PembayaranMaster> tbl_PembayaranMasters
		{
			get
			{
				return this._tbl_PembayaranMasters;
			}
			set
			{
				this._tbl_PembayaranMasters.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Antrian_tbl_Diagnosa", Storage="_tbl_Antrian", ThisKey="id", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Antrian tbl_Antrian
		{
			get
			{
				return this._tbl_Antrian.Entity;
			}
			set
			{
				tbl_Antrian previousValue = this._tbl_Antrian.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Antrian.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Antrian.Entity = null;
						previousValue.tbl_Diagnosas.Remove(this);
					}
					this._tbl_Antrian.Entity = value;
					if ((value != null))
					{
						value.tbl_Diagnosas.Add(this);
						this._id = value.id;
					}
					else
					{
						this._id = default(int);
					}
					this.SendPropertyChanged("tbl_Antrian");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PembayaranMasters(tbl_PembayaranMaster entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Diagnosa = this;
		}
		
		private void detach_tbl_PembayaranMasters(tbl_PembayaranMaster entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Diagnosa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Dokter")]
	public partial class tbl_Dokter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dokter;
		
		private string _nama;
		
		private string _jenis_kelamin;
		
		private System.DateTime _tanggal_lahir;
		
		private string _alamat;
		
		private string _kota;
		
		private int _kodepos;
		
		private string _telepon;
		
		private string _email;
		
		private EntitySet<tbl_Ruangan> _tbl_Ruangans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dokterChanging(int value);
    partial void Onid_dokterChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void Onjenis_kelaminChanging(string value);
    partial void Onjenis_kelaminChanged();
    partial void Ontanggal_lahirChanging(System.DateTime value);
    partial void Ontanggal_lahirChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void OnkotaChanging(string value);
    partial void OnkotaChanged();
    partial void OnkodeposChanging(int value);
    partial void OnkodeposChanged();
    partial void OnteleponChanging(string value);
    partial void OnteleponChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public tbl_Dokter()
		{
			this._tbl_Ruangans = new EntitySet<tbl_Ruangan>(new Action<tbl_Ruangan>(this.attach_tbl_Ruangans), new Action<tbl_Ruangan>(this.detach_tbl_Ruangans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dokter", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_dokter
		{
			get
			{
				return this._id_dokter;
			}
			set
			{
				if ((this._id_dokter != value))
				{
					this.Onid_dokterChanging(value);
					this.SendPropertyChanging();
					this._id_dokter = value;
					this.SendPropertyChanged("id_dokter");
					this.Onid_dokterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_kelamin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jenis_kelamin
		{
			get
			{
				return this._jenis_kelamin;
			}
			set
			{
				if ((this._jenis_kelamin != value))
				{
					this.Onjenis_kelaminChanging(value);
					this.SendPropertyChanging();
					this._jenis_kelamin = value;
					this.SendPropertyChanged("jenis_kelamin");
					this.Onjenis_kelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal_lahir", DbType="Date NOT NULL")]
		public System.DateTime tanggal_lahir
		{
			get
			{
				return this._tanggal_lahir;
			}
			set
			{
				if ((this._tanggal_lahir != value))
				{
					this.Ontanggal_lahirChanging(value);
					this.SendPropertyChanging();
					this._tanggal_lahir = value;
					this.SendPropertyChanged("tanggal_lahir");
					this.Ontanggal_lahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kota", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string kota
		{
			get
			{
				return this._kota;
			}
			set
			{
				if ((this._kota != value))
				{
					this.OnkotaChanging(value);
					this.SendPropertyChanging();
					this._kota = value;
					this.SendPropertyChanged("kota");
					this.OnkotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodepos", DbType="Int NOT NULL")]
		public int kodepos
		{
			get
			{
				return this._kodepos;
			}
			set
			{
				if ((this._kodepos != value))
				{
					this.OnkodeposChanging(value);
					this.SendPropertyChanging();
					this._kodepos = value;
					this.SendPropertyChanged("kodepos");
					this.OnkodeposChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telepon", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telepon
		{
			get
			{
				return this._telepon;
			}
			set
			{
				if ((this._telepon != value))
				{
					this.OnteleponChanging(value);
					this.SendPropertyChanging();
					this._telepon = value;
					this.SendPropertyChanged("telepon");
					this.OnteleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Dokter_tbl_Ruangan", Storage="_tbl_Ruangans", ThisKey="id_dokter", OtherKey="id_dokter")]
		public EntitySet<tbl_Ruangan> tbl_Ruangans
		{
			get
			{
				return this._tbl_Ruangans;
			}
			set
			{
				this._tbl_Ruangans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Ruangans(tbl_Ruangan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Dokter = this;
		}
		
		private void detach_tbl_Ruangans(tbl_Ruangan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Dokter = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Jadwal")]
	public partial class tbl_Jadwal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_jadwal;
		
		private System.TimeSpan _mulai;
		
		private System.TimeSpan _selesai;
		
		private EntitySet<tbl_Ruangan> _tbl_Ruangans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_jadwalChanging(string value);
    partial void Onid_jadwalChanged();
    partial void OnmulaiChanging(System.TimeSpan value);
    partial void OnmulaiChanged();
    partial void OnselesaiChanging(System.TimeSpan value);
    partial void OnselesaiChanged();
    #endregion
		
		public tbl_Jadwal()
		{
			this._tbl_Ruangans = new EntitySet<tbl_Ruangan>(new Action<tbl_Ruangan>(this.attach_tbl_Ruangans), new Action<tbl_Ruangan>(this.detach_tbl_Ruangans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jadwal", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_jadwal
		{
			get
			{
				return this._id_jadwal;
			}
			set
			{
				if ((this._id_jadwal != value))
				{
					this.Onid_jadwalChanging(value);
					this.SendPropertyChanging();
					this._id_jadwal = value;
					this.SendPropertyChanged("id_jadwal");
					this.Onid_jadwalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mulai", DbType="Time NOT NULL")]
		public System.TimeSpan mulai
		{
			get
			{
				return this._mulai;
			}
			set
			{
				if ((this._mulai != value))
				{
					this.OnmulaiChanging(value);
					this.SendPropertyChanging();
					this._mulai = value;
					this.SendPropertyChanged("mulai");
					this.OnmulaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selesai", DbType="Time NOT NULL")]
		public System.TimeSpan selesai
		{
			get
			{
				return this._selesai;
			}
			set
			{
				if ((this._selesai != value))
				{
					this.OnselesaiChanging(value);
					this.SendPropertyChanging();
					this._selesai = value;
					this.SendPropertyChanged("selesai");
					this.OnselesaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jadwal_tbl_Ruangan", Storage="_tbl_Ruangans", ThisKey="id_jadwal", OtherKey="id_jadwal")]
		public EntitySet<tbl_Ruangan> tbl_Ruangans
		{
			get
			{
				return this._tbl_Ruangans;
			}
			set
			{
				this._tbl_Ruangans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Ruangans(tbl_Ruangan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Jadwal = this;
		}
		
		private void detach_tbl_Ruangans(tbl_Ruangan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Jadwal = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Obat")]
	public partial class tbl_Obat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_obat;
		
		private string _nama_obat;
		
		private double _harga;
		
		private int _stok;
		
		private EntitySet<tbl_PembayaranDetail> _tbl_PembayaranDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_obatChanging(int value);
    partial void Onid_obatChanged();
    partial void Onnama_obatChanging(string value);
    partial void Onnama_obatChanged();
    partial void OnhargaChanging(double value);
    partial void OnhargaChanged();
    partial void OnstokChanging(int value);
    partial void OnstokChanged();
    #endregion
		
		public tbl_Obat()
		{
			this._tbl_PembayaranDetails = new EntitySet<tbl_PembayaranDetail>(new Action<tbl_PembayaranDetail>(this.attach_tbl_PembayaranDetails), new Action<tbl_PembayaranDetail>(this.detach_tbl_PembayaranDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_obat", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_obat
		{
			get
			{
				return this._id_obat;
			}
			set
			{
				if ((this._id_obat != value))
				{
					this.Onid_obatChanging(value);
					this.SendPropertyChanging();
					this._id_obat = value;
					this.SendPropertyChanged("id_obat");
					this.Onid_obatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_obat", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nama_obat
		{
			get
			{
				return this._nama_obat;
			}
			set
			{
				if ((this._nama_obat != value))
				{
					this.Onnama_obatChanging(value);
					this.SendPropertyChanging();
					this._nama_obat = value;
					this.SendPropertyChanged("nama_obat");
					this.Onnama_obatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Float NOT NULL")]
		public double harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this.OnhargaChanging(value);
					this.SendPropertyChanging();
					this._harga = value;
					this.SendPropertyChanged("harga");
					this.OnhargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stok", DbType="Int NOT NULL")]
		public int stok
		{
			get
			{
				return this._stok;
			}
			set
			{
				if ((this._stok != value))
				{
					this.OnstokChanging(value);
					this.SendPropertyChanging();
					this._stok = value;
					this.SendPropertyChanged("stok");
					this.OnstokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Obat_tbl_PembayaranDetail", Storage="_tbl_PembayaranDetails", ThisKey="id_obat", OtherKey="id_obat")]
		public EntitySet<tbl_PembayaranDetail> tbl_PembayaranDetails
		{
			get
			{
				return this._tbl_PembayaranDetails;
			}
			set
			{
				this._tbl_PembayaranDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PembayaranDetails(tbl_PembayaranDetail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Obat = this;
		}
		
		private void detach_tbl_PembayaranDetails(tbl_PembayaranDetail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Obat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PembayaranDetail")]
	public partial class tbl_PembayaranDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _auto;
		
		private string _id_pembayaran;
		
		private int _id_obat;
		
		private int _jumlah;
		
		private double _harga;
		
		private EntityRef<tbl_Obat> _tbl_Obat;
		
		private EntityRef<tbl_PembayaranMaster> _tbl_PembayaranMaster;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnautoChanging(int value);
    partial void OnautoChanged();
    partial void Onid_pembayaranChanging(string value);
    partial void Onid_pembayaranChanged();
    partial void Onid_obatChanging(int value);
    partial void Onid_obatChanged();
    partial void OnjumlahChanging(int value);
    partial void OnjumlahChanged();
    partial void OnhargaChanging(double value);
    partial void OnhargaChanged();
    #endregion
		
		public tbl_PembayaranDetail()
		{
			this._tbl_Obat = default(EntityRef<tbl_Obat>);
			this._tbl_PembayaranMaster = default(EntityRef<tbl_PembayaranMaster>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int auto
		{
			get
			{
				return this._auto;
			}
			set
			{
				if ((this._auto != value))
				{
					this.OnautoChanging(value);
					this.SendPropertyChanging();
					this._auto = value;
					this.SendPropertyChanged("auto");
					this.OnautoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembayaran", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_pembayaran
		{
			get
			{
				return this._id_pembayaran;
			}
			set
			{
				if ((this._id_pembayaran != value))
				{
					if (this._tbl_PembayaranMaster.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pembayaranChanging(value);
					this.SendPropertyChanging();
					this._id_pembayaran = value;
					this.SendPropertyChanged("id_pembayaran");
					this.Onid_pembayaranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_obat", DbType="Int NOT NULL")]
		public int id_obat
		{
			get
			{
				return this._id_obat;
			}
			set
			{
				if ((this._id_obat != value))
				{
					if (this._tbl_Obat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_obatChanging(value);
					this.SendPropertyChanging();
					this._id_obat = value;
					this.SendPropertyChanged("id_obat");
					this.Onid_obatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jumlah", DbType="Int NOT NULL")]
		public int jumlah
		{
			get
			{
				return this._jumlah;
			}
			set
			{
				if ((this._jumlah != value))
				{
					this.OnjumlahChanging(value);
					this.SendPropertyChanging();
					this._jumlah = value;
					this.SendPropertyChanged("jumlah");
					this.OnjumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Float NOT NULL")]
		public double harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this.OnhargaChanging(value);
					this.SendPropertyChanging();
					this._harga = value;
					this.SendPropertyChanged("harga");
					this.OnhargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Obat_tbl_PembayaranDetail", Storage="_tbl_Obat", ThisKey="id_obat", OtherKey="id_obat", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Obat tbl_Obat
		{
			get
			{
				return this._tbl_Obat.Entity;
			}
			set
			{
				tbl_Obat previousValue = this._tbl_Obat.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Obat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Obat.Entity = null;
						previousValue.tbl_PembayaranDetails.Remove(this);
					}
					this._tbl_Obat.Entity = value;
					if ((value != null))
					{
						value.tbl_PembayaranDetails.Add(this);
						this._id_obat = value.id_obat;
					}
					else
					{
						this._id_obat = default(int);
					}
					this.SendPropertyChanged("tbl_Obat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PembayaranMaster_tbl_PembayaranDetail", Storage="_tbl_PembayaranMaster", ThisKey="id_pembayaran", OtherKey="id_pembayaran", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_PembayaranMaster tbl_PembayaranMaster
		{
			get
			{
				return this._tbl_PembayaranMaster.Entity;
			}
			set
			{
				tbl_PembayaranMaster previousValue = this._tbl_PembayaranMaster.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PembayaranMaster.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PembayaranMaster.Entity = null;
						previousValue.tbl_PembayaranDetails.Remove(this);
					}
					this._tbl_PembayaranMaster.Entity = value;
					if ((value != null))
					{
						value.tbl_PembayaranDetails.Add(this);
						this._id_pembayaran = value.id_pembayaran;
					}
					else
					{
						this._id_pembayaran = default(string);
					}
					this.SendPropertyChanged("tbl_PembayaranMaster");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PembayaranMaster")]
	public partial class tbl_PembayaranMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_pembayaran;
		
		private string _id_diagnosa;
		
		private double _total;
		
		private System.DateTime _waktu_pembayaran;
		
		private EntitySet<tbl_PembayaranDetail> _tbl_PembayaranDetails;
		
		private EntityRef<tbl_Diagnosa> _tbl_Diagnosa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pembayaranChanging(string value);
    partial void Onid_pembayaranChanged();
    partial void Onid_diagnosaChanging(string value);
    partial void Onid_diagnosaChanged();
    partial void OntotalChanging(double value);
    partial void OntotalChanged();
    partial void Onwaktu_pembayaranChanging(System.DateTime value);
    partial void Onwaktu_pembayaranChanged();
    #endregion
		
		public tbl_PembayaranMaster()
		{
			this._tbl_PembayaranDetails = new EntitySet<tbl_PembayaranDetail>(new Action<tbl_PembayaranDetail>(this.attach_tbl_PembayaranDetails), new Action<tbl_PembayaranDetail>(this.detach_tbl_PembayaranDetails));
			this._tbl_Diagnosa = default(EntityRef<tbl_Diagnosa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembayaran", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_pembayaran
		{
			get
			{
				return this._id_pembayaran;
			}
			set
			{
				if ((this._id_pembayaran != value))
				{
					this.Onid_pembayaranChanging(value);
					this.SendPropertyChanging();
					this._id_pembayaran = value;
					this.SendPropertyChanged("id_pembayaran");
					this.Onid_pembayaranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_diagnosa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_diagnosa
		{
			get
			{
				return this._id_diagnosa;
			}
			set
			{
				if ((this._id_diagnosa != value))
				{
					if (this._tbl_Diagnosa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_diagnosaChanging(value);
					this.SendPropertyChanging();
					this._id_diagnosa = value;
					this.SendPropertyChanged("id_diagnosa");
					this.Onid_diagnosaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Float NOT NULL")]
		public double total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waktu_pembayaran", DbType="DateTime NOT NULL")]
		public System.DateTime waktu_pembayaran
		{
			get
			{
				return this._waktu_pembayaran;
			}
			set
			{
				if ((this._waktu_pembayaran != value))
				{
					this.Onwaktu_pembayaranChanging(value);
					this.SendPropertyChanging();
					this._waktu_pembayaran = value;
					this.SendPropertyChanged("waktu_pembayaran");
					this.Onwaktu_pembayaranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PembayaranMaster_tbl_PembayaranDetail", Storage="_tbl_PembayaranDetails", ThisKey="id_pembayaran", OtherKey="id_pembayaran")]
		public EntitySet<tbl_PembayaranDetail> tbl_PembayaranDetails
		{
			get
			{
				return this._tbl_PembayaranDetails;
			}
			set
			{
				this._tbl_PembayaranDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Diagnosa_tbl_PembayaranMaster", Storage="_tbl_Diagnosa", ThisKey="id_diagnosa", OtherKey="id_diagnosa", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Diagnosa tbl_Diagnosa
		{
			get
			{
				return this._tbl_Diagnosa.Entity;
			}
			set
			{
				tbl_Diagnosa previousValue = this._tbl_Diagnosa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Diagnosa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Diagnosa.Entity = null;
						previousValue.tbl_PembayaranMasters.Remove(this);
					}
					this._tbl_Diagnosa.Entity = value;
					if ((value != null))
					{
						value.tbl_PembayaranMasters.Add(this);
						this._id_diagnosa = value.id_diagnosa;
					}
					else
					{
						this._id_diagnosa = default(string);
					}
					this.SendPropertyChanged("tbl_Diagnosa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PembayaranDetails(tbl_PembayaranDetail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PembayaranMaster = this;
		}
		
		private void detach_tbl_PembayaranDetails(tbl_PembayaranDetail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PembayaranMaster = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Ruangan")]
	public partial class tbl_Ruangan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_ruangan;
		
		private string _nama_ruangan;
		
		private string _id_tipe;
		
		private int _id_dokter;
		
		private string _id_jadwal;
		
		private string _status;
		
		private EntitySet<tbl_Antrian> _tbl_Antrians;
		
		private EntityRef<tbl_Dokter> _tbl_Dokter;
		
		private EntityRef<tbl_Jadwal> _tbl_Jadwal;
		
		private EntityRef<tbl_tipe> _tbl_tipe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ruanganChanging(string value);
    partial void Onid_ruanganChanged();
    partial void Onnama_ruanganChanging(string value);
    partial void Onnama_ruanganChanged();
    partial void Onid_tipeChanging(string value);
    partial void Onid_tipeChanged();
    partial void Onid_dokterChanging(int value);
    partial void Onid_dokterChanged();
    partial void Onid_jadwalChanging(string value);
    partial void Onid_jadwalChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public tbl_Ruangan()
		{
			this._tbl_Antrians = new EntitySet<tbl_Antrian>(new Action<tbl_Antrian>(this.attach_tbl_Antrians), new Action<tbl_Antrian>(this.detach_tbl_Antrians));
			this._tbl_Dokter = default(EntityRef<tbl_Dokter>);
			this._tbl_Jadwal = default(EntityRef<tbl_Jadwal>);
			this._tbl_tipe = default(EntityRef<tbl_tipe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ruangan", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_ruangan
		{
			get
			{
				return this._id_ruangan;
			}
			set
			{
				if ((this._id_ruangan != value))
				{
					this.Onid_ruanganChanging(value);
					this.SendPropertyChanging();
					this._id_ruangan = value;
					this.SendPropertyChanged("id_ruangan");
					this.Onid_ruanganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_ruangan", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nama_ruangan
		{
			get
			{
				return this._nama_ruangan;
			}
			set
			{
				if ((this._nama_ruangan != value))
				{
					this.Onnama_ruanganChanging(value);
					this.SendPropertyChanging();
					this._nama_ruangan = value;
					this.SendPropertyChanged("nama_ruangan");
					this.Onnama_ruanganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipe", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_tipe
		{
			get
			{
				return this._id_tipe;
			}
			set
			{
				if ((this._id_tipe != value))
				{
					if (this._tbl_tipe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipeChanging(value);
					this.SendPropertyChanging();
					this._id_tipe = value;
					this.SendPropertyChanged("id_tipe");
					this.Onid_tipeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dokter", DbType="Int NOT NULL")]
		public int id_dokter
		{
			get
			{
				return this._id_dokter;
			}
			set
			{
				if ((this._id_dokter != value))
				{
					if (this._tbl_Dokter.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_dokterChanging(value);
					this.SendPropertyChanging();
					this._id_dokter = value;
					this.SendPropertyChanged("id_dokter");
					this.Onid_dokterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jadwal", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_jadwal
		{
			get
			{
				return this._id_jadwal;
			}
			set
			{
				if ((this._id_jadwal != value))
				{
					if (this._tbl_Jadwal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_jadwalChanging(value);
					this.SendPropertyChanging();
					this._id_jadwal = value;
					this.SendPropertyChanged("id_jadwal");
					this.Onid_jadwalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Ruangan_tbl_Antrian", Storage="_tbl_Antrians", ThisKey="id_ruangan", OtherKey="id_ruangan")]
		public EntitySet<tbl_Antrian> tbl_Antrians
		{
			get
			{
				return this._tbl_Antrians;
			}
			set
			{
				this._tbl_Antrians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Dokter_tbl_Ruangan", Storage="_tbl_Dokter", ThisKey="id_dokter", OtherKey="id_dokter", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Dokter tbl_Dokter
		{
			get
			{
				return this._tbl_Dokter.Entity;
			}
			set
			{
				tbl_Dokter previousValue = this._tbl_Dokter.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Dokter.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Dokter.Entity = null;
						previousValue.tbl_Ruangans.Remove(this);
					}
					this._tbl_Dokter.Entity = value;
					if ((value != null))
					{
						value.tbl_Ruangans.Add(this);
						this._id_dokter = value.id_dokter;
					}
					else
					{
						this._id_dokter = default(int);
					}
					this.SendPropertyChanged("tbl_Dokter");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jadwal_tbl_Ruangan", Storage="_tbl_Jadwal", ThisKey="id_jadwal", OtherKey="id_jadwal", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Jadwal tbl_Jadwal
		{
			get
			{
				return this._tbl_Jadwal.Entity;
			}
			set
			{
				tbl_Jadwal previousValue = this._tbl_Jadwal.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Jadwal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Jadwal.Entity = null;
						previousValue.tbl_Ruangans.Remove(this);
					}
					this._tbl_Jadwal.Entity = value;
					if ((value != null))
					{
						value.tbl_Ruangans.Add(this);
						this._id_jadwal = value.id_jadwal;
					}
					else
					{
						this._id_jadwal = default(string);
					}
					this.SendPropertyChanged("tbl_Jadwal");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipe_tbl_Ruangan", Storage="_tbl_tipe", ThisKey="id_tipe", OtherKey="id_tipe", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_tipe tbl_tipe
		{
			get
			{
				return this._tbl_tipe.Entity;
			}
			set
			{
				tbl_tipe previousValue = this._tbl_tipe.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tipe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tipe.Entity = null;
						previousValue.tbl_Ruangans.Remove(this);
					}
					this._tbl_tipe.Entity = value;
					if ((value != null))
					{
						value.tbl_Ruangans.Add(this);
						this._id_tipe = value.id_tipe;
					}
					else
					{
						this._id_tipe = default(string);
					}
					this.SendPropertyChanged("tbl_tipe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Antrians(tbl_Antrian entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Ruangan = this;
		}
		
		private void detach_tbl_Antrians(tbl_Antrian entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Ruangan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tipe")]
	public partial class tbl_tipe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_tipe;
		
		private string _nama;
		
		private EntitySet<tbl_Ruangan> _tbl_Ruangans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipeChanging(string value);
    partial void Onid_tipeChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    #endregion
		
		public tbl_tipe()
		{
			this._tbl_Ruangans = new EntitySet<tbl_Ruangan>(new Action<tbl_Ruangan>(this.attach_tbl_Ruangans), new Action<tbl_Ruangan>(this.detach_tbl_Ruangans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipe", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_tipe
		{
			get
			{
				return this._id_tipe;
			}
			set
			{
				if ((this._id_tipe != value))
				{
					this.Onid_tipeChanging(value);
					this.SendPropertyChanging();
					this._id_tipe = value;
					this.SendPropertyChanged("id_tipe");
					this.Onid_tipeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipe_tbl_Ruangan", Storage="_tbl_Ruangans", ThisKey="id_tipe", OtherKey="id_tipe")]
		public EntitySet<tbl_Ruangan> tbl_Ruangans
		{
			get
			{
				return this._tbl_Ruangans;
			}
			set
			{
				this._tbl_Ruangans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Ruangans(tbl_Ruangan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipe = this;
		}
		
		private void detach_tbl_Ruangans(tbl_Ruangan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipe = null;
		}
	}
}
#pragma warning restore 1591
